name: End-to-end tests
on: push
jobs:
  cypress-run:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      # Install npm dependencies, cache them correctly
      # and run all Cypress tests
      - name: Cypress run
        uses: cypress-io/github-action@v6
      #On Sucess
      - name: Notify on Success
        if: success()
        run: echo "All tests passed successfully!"
      #on failure
      - name: Notify on Failure
        if: failure()
        run: |
          echo "Tests failed. Sending failure details..."
          for file in results/*.xml; do
            echo "Parsing $file..."
            cypress-failed-log-parser "$file"
          done